// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SistemaApiIdwall.Context;

#nullable disable

namespace SistemaAPIidwall.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaApiIdwall.Model.NacionalidadeModel", b =>
                {
                    b.Property<string>("NacionalidadeId")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("NACIONALIDADEID");

                    b.Property<string>("NacionalidadeDesc")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NACIONALIDADEDESC");

                    b.HasKey("NacionalidadeId");

                    b.ToTable("TB_NACIONALIDADES");
                });

            modelBuilder.Entity("SistemaApiIdwall.Model.SuspeitosModel", b =>
                {
                    b.Property<int>("SuspeitoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SUSPEITOID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuspeitoId"));

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLASSIFICACAO");

                    b.Property<string>("NacionalidadeId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("NomeSuspeito")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOMESUSPEITO");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SEXO");

                    b.HasKey("SuspeitoId");

                    b.HasIndex("NacionalidadeId")
                        .IsUnique();

                    b.ToTable("PESSOAS");
                });

            modelBuilder.Entity("SistemaApiIdwall.Model.SuspeitosModel", b =>
                {
                    b.HasOne("SistemaApiIdwall.Model.NacionalidadeModel", "NacionalidadeModel")
                        .WithOne("SuspeitosModel")
                        .HasForeignKey("SistemaApiIdwall.Model.SuspeitosModel", "NacionalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NacionalidadeModel");
                });

            modelBuilder.Entity("SistemaApiIdwall.Model.NacionalidadeModel", b =>
                {
                    b.Navigation("SuspeitosModel")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
